### ISSUE TITLE
Finish rubocop formatting and re-include problem directories

### ISSUE THREAD

**Issue by lortza** [lortza/therapy_tracker#53]
I've been chipping away at rubocop fixes and there are still 3 problematic directories left. 

- app/channels
- app/helpers
- app/models

Some of these changes require business decisions, which is why I set them aside to handle later. Once these changes are made and the files will pass, update the rubocop file to remove these 3 directories from the exclusions:

```
AllCops:
  DefaultFormatter: progress
  Exclude:
    - 'app/channels/**/*'
    - 'app/helpers/*'
    - 'app/models/*'
```

Also, be sure to turn on rubocop in travis:
```
script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake db:seed
  # - bundle exec rubocop
```

## To Do
- [x] enable rubocop in ci
- [x] fix app/channels
- [x] fix app/helpers
- [ ] fix app/models
- [ ] remove those directories from the exclude block
